# Generated by Django 5.2.5 on 2025-09-05 02:08

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0004_remove_producto_cantidad_inventario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioProducto',
            fields=[
            ],
            options={
                'verbose_name': 'Inventario Producto',
                'verbose_name_plural': 'Inventario Productos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('productos.producto',),
        ),
    ]
