# Generated by Django 5.2.5 on 2025-10-21 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventarioproducto',
            options={'ordering': ['nombre'], 'verbose_name': 'Inventario Producto', 'verbose_name_plural': 'Inventario Productos'},
        ),
    ]
