# Generated by Django 5.2.5 on 2025-10-21 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_inventarioproducto_options'),
        ('productos', '0005_clasificacionproducto_grupoproducto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlmacenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodega', models.CharField(max_length=100, verbose_name='Bodega')),
                ('seccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sección')),
                ('estante', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estante')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='almacen', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Almacen Producto',
                'verbose_name_plural': 'Almacenes de Productos',
                'ordering': ['producto__nombre'],
            },
        ),
    ]
