# Generated by Django 5.2.5 on 2025-10-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_almacenproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacenproducto',
            name='bodega',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bodega'),
        ),
    ]
