# Generated by Django 5.2.5 on 2025-09-02 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0004_remove_producto_cantidad_inventario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.IntegerField(choices=[(1, 'Angela Davila'), (2, 'Rocio Leon'), (3, 'Edwin Davila'), (4, 'Rafael Clavijo'), (5, 'Veronica Gomez'), (6, 'Maria Susana'), (7, 'Jazzmin Gonzales')])),
                ('numero_pedido', models.CharField(editable=False, max_length=20, unique=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('nombre_producto', models.CharField(blank=True, max_length=150)),
                ('precio1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('registro_sanitario', models.CharField(blank=True, max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=50)),
                ('fecha_elaboracion', models.DateField(blank=True, null=True)),
                ('vigencia_lote', models.DateField(blank=True, null=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.productolote')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_preparacion', models.DateTimeField(blank=True, null=True)),
                ('fin_preparacion', models.DateTimeField(blank=True, null=True)),
                ('responsable_preparacion', models.CharField(blank=True, choices=[('Randy', 'Randy'), ('Esteban', 'Esteban'), ('Rafael', 'Rafael'), ('Guillermo', 'Guillermo'), ('Edwin', 'Edwin'), ('Orlando', 'Orlando')], max_length=50)),
                ('responsable_revision', models.CharField(blank=True, choices=[('Randy', 'Randy'), ('Esteban', 'Esteban'), ('Rafael', 'Rafael'), ('Guillermo', 'Guillermo'), ('Edwin', 'Edwin'), ('Orlando', 'Orlando')], max_length=50)),
                ('numero_guia', models.CharField(blank=True, max_length=50)),
                ('cantidad_cajas', models.PositiveIntegerField(blank=True, null=True)),
                ('flete', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fin_despacho', models.DateTimeField(blank=True, null=True)),
                ('cerrado', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='pedidos.pedido')),
            ],
        ),
    ]
