# Generated by Django 5.2.5 on 2025-09-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodetalle',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
