# Generated by Django 5.2.5 on 2025-09-02 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedidodetalle_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
