# Generated by Django 5.2.5 on 2025-09-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_tracking_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='aprobado',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
    ]
