# Generated by Django 5.2.5 on 2025-10-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='provincia',
            field=models.CharField(blank=True, choices=[('Azuay', 'Azuay'), ('Bolívar', 'Bolívar'), ('Cañar', 'Cañar'), ('Carchi', 'Carchi'), ('Chimborazo', 'Chimborazo'), ('Cotopaxi', 'Cotopaxi'), ('El Oro', 'El Oro'), ('Esmeraldas', 'Esmeraldas'), ('Galápagos', 'Galápagos'), ('Guayas', 'Guayas'), ('Imbabura', 'Imbabura'), ('Loja', 'Loja'), ('Los Ríos', 'Los Ríos'), ('Manabí', 'Manabí'), ('Morona Santiago', 'Morona Santiago'), ('Napo', 'Napo'), ('Orellana', 'Orellana'), ('Pastaza', 'Pastaza'), ('Pichincha', 'Pichincha'), ('Santa Elena', 'Santa Elena'), ('Santo Domingo', 'Santo Domingo'), ('Sucumbíos', 'Sucumbíos'), ('Tungurahua', 'Tungurahua'), ('Zamora Chinchipe', 'Zamora Chinchipe')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='requiere_envio',
            field=models.BooleanField(default=False, verbose_name='¿Requiere envío?'),
        ),
    ]
