# Generated by Django 5.2.5 on 2025-08-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del Producto')),
                ('lote', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote')),
                ('fecha_elaboracion', models.DateField(verbose_name='Fecha de Elaboración')),
                ('vigencia_lote', models.DateField(blank=True, null=True, verbose_name='Vigencia del Lote')),
                ('registro_sanitario', models.CharField(max_length=100, verbose_name='Registro Sanitario')),
                ('ubicacion', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('OUTLET', 'Outlet'), ('CUARENTENA', 'Cuarentena')], max_length=20, verbose_name='Ubicación')),
                ('precio1', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio 1')),
                ('precio2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio 2')),
                ('precio3', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio 3')),
            ],
        ),
    ]
