# Generated by Django 5.2.5 on 2025-08-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100, verbose_name='Nombre del Producto'),
        ),
    ]
