# Generated by Django 5.2.5 on 2025-08-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_inventario',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad en Inventario'),
        ),
    ]
