# Generated by Django 5.2.5 on 2025-08-27 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_cantidad_inventario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_inventario',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_elaboracion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='vigencia_lote',
        ),
        migrations.CreateModel(
            name='ProductoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=50, verbose_name='Lote')),
                ('fecha_elaboracion', models.DateField(verbose_name='Fecha de Elaboración')),
                ('vigencia_lote', models.DateField(verbose_name='Vigencia del Lote')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Lote de Producto',
                'verbose_name_plural': 'Lotes de Productos',
                'unique_together': {('producto', 'lote', 'vigencia_lote')},
            },
        ),
    ]
