# Generated by Django 5.2.5 on 2025-10-21 05:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_producto_cantidad_inventario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código de Clasificación')),
                ('descripcion', models.CharField(choices=[('GUANTES_LATEX_ESTERILES', 'Guantes de Látex Estériles'), ('GUANTES_NITRILO_NO_ESTERILES', 'Guantes de Nitrilo No Estériles'), ('JERINGAS_3ML', 'Jeringas Desechables 3ml'), ('JERINGAS_5ML', 'Jeringas Desechables 5ml'), ('JERINGAS_10ML', 'Jeringas Desechables 10ml'), ('AGUJAS_21G', 'Agujas Hipodérmicas 21G'), ('AGUJAS_23G', 'Agujas Hipodérmicas 23G'), ('AGUJAS_25G', 'Agujas Hipodérmicas 25G'), ('GASAS_10x10', 'Gasas Estériles 10x10'), ('GASAS_20x20', 'Gasas Estériles 20x20'), ('APOSITOS_NO_ADHERENTES', 'Apósitos No Adherentes'), ('SONDAS_FOLEY', 'Sondas Foley Pediátricas/Adultas'), ('CATETER_IV', 'Catéteres Intravenosos'), ('SUTURAS_NYLON', 'Suturas Nylon'), ('SUTURAS_SEDA', 'Suturas Seda'), ('SUTURAS_POLIESTER', 'Suturas Poliéster'), ('SOLUCION_SALINA', 'Solución Salina 0.9%'), ('SOLUCION_GLUCO_5', 'Solución Glucosada 5%'), ('ALCOHOL_70', 'Alcohol Isopropílico 70%'), ('POVIDONA_YODADA', 'Povidona Yodada'), ('VENDAJE_ELASTICO', 'Vendajes Elásticos 10cm, 15cm'), ('VENDAJE_YESO', 'Vendajes de Yeso 5cm, 10cm')], max_length=200, verbose_name='Descripción de Clasificación')),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Proveedor Asociado')),
            ],
            options={
                'verbose_name': 'Clasificación de Producto',
                'verbose_name_plural': 'Clasificaciones de Productos',
                'ordering': ['subgrupo__grupo__codigo', 'subgrupo__codigo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='GrupoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de Grupo')),
                ('descripcion', models.CharField(choices=[('MATERIAL_QUIRURGICO', 'Material Quirúrgico y Hospitalario'), ('MEDICAMENTOS', 'Medicamentos y Farmacéuticos'), ('EQUIPO_MEDICO', 'Equipo Médico y Diagnóstico'), ('MATERIAL_CURACION', 'Material de Curación y Desechables'), ('PRODUCTOS_HIGIENE', 'Productos de Higiene y Asepsia')], max_length=200, verbose_name='Descripción del Grupo')),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Proveedor Asociado')),
            ],
            options={
                'verbose_name': 'Grupo de Producto',
                'verbose_name_plural': 'Grupos de Productos',
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productolote',
            options={'ordering': ['vigencia_lote'], 'verbose_name': 'Lote de Producto', 'verbose_name_plural': 'Lotes de Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Detallada'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ean13',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Código EAN-13'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ean14',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Código EAN-14'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_especial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Especial'),
        ),
        migrations.AddField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Presentación'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor_principal',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Proveedor Principal'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Mínimo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad de Medida'),
        ),
        migrations.AddField(
            model_name='producto',
            name='vigencia_registro',
            field=models.DateField(blank=True, null=True, verbose_name='Vigencia del Registro Sanitario'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='registro_sanitario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Registro Sanitario'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(choices=[('PRINCIPAL', 'Principal'), ('OUTLET', 'Outlet'), ('CUARENTENA', 'Cuarentena')], default='PRINCIPAL', max_length=20, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='productolote',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Disponible'),
        ),
        migrations.AlterField(
            model_name='productolote',
            name='fecha_elaboracion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elaboración'),
        ),
        migrations.AlterField(
            model_name='productolote',
            name='lote',
            field=models.CharField(max_length=50, verbose_name='Número de Lote'),
        ),
        migrations.AlterField(
            model_name='productolote',
            name='vigencia_lote',
            field=models.DateField(blank=True, null=True, verbose_name='Vigencia del Lote'),
        ),
        migrations.AddField(
            model_name='producto',
            name='clasificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.clasificacionproducto', verbose_name='Clasificación'),
        ),
        migrations.AddField(
            model_name='producto',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.grupoproducto', verbose_name='Grupo'),
        ),
        migrations.CreateModel(
            name='SubgrupoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código de Subgrupo')),
                ('descripcion', models.CharField(choices=[('GUANTES', 'Guantes de Examen y Quirúrgicos'), ('JERINGAS', 'Jeringas y Agujas Estériles'), ('GASAS', 'Gasas y Apósitos'), ('SONDAS', 'Sondas y Catéteres'), ('SUTURAS', 'Suturas y Material de Sutura'), ('SOLUCIONES_IV', 'Soluciones Intravenosas'), ('ANTISEPTICOS', 'Antisépticos y Desinfectantes'), ('VENDAJES', 'Vendajes e Inmovilizadores')], max_length=200, verbose_name='Descripción del Subgrupo')),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Proveedor Asociado')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgrupos', to='productos.grupoproducto', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Subgrupo de Producto',
                'verbose_name_plural': 'Subgrupos de Productos',
                'ordering': ['grupo__codigo', 'codigo'],
                'unique_together': {('grupo', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='clasificacionproducto',
            name='subgrupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones', to='productos.subgrupoproducto', verbose_name='Subgrupo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='subgrupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.subgrupoproducto', verbose_name='Subgrupo'),
        ),
        migrations.AlterUniqueTogether(
            name='clasificacionproducto',
            unique_together={('subgrupo', 'codigo')},
        ),
    ]
