# Generated by Django 5.2.5 on 2025-08-27 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CEDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte'), ('RUC', 'RUC')], max_length=10, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=13, unique=True, verbose_name='Número de Documento')),
                ('nombre_completo', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El campo solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$'), django.core.validators.MinLengthValidator(2)], verbose_name='Nombre Completo')),
                ('telefono_movil', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El campo solo puede contener números.', regex='^\\d+$'), django.core.validators.MinLengthValidator(7)], verbose_name='Teléfono Móvil')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('direccion', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Dirección')),
                ('provincia', models.CharField(choices=[('AZUAY', 'Azuay'), ('BOLIVAR', 'Bolívar'), ('CAÑAR', 'Cañar'), ('CARCHI', 'Carchi'), ('CHIMBORAZO', 'Chimborazo'), ('COTOPAXI', 'Cotopaxi'), ('EL_ORO', 'El Oro'), ('ESMERALDAS', 'Esmeraldas'), ('GUAYAS', 'Guayas'), ('IMBABURA', 'Imbabura'), ('LOJA', 'Loja'), ('LOS_RIOS', 'Los Ríos'), ('MANABI', 'Manabí'), ('MORONA_SANTIAGO', 'Morona Santiago'), ('NAPO', 'Napo'), ('PASTAZA', 'Pastaza'), ('PICHINCHA', 'Pichincha'), ('TUNGURAHUA', 'Tungurahua'), ('ZAMORA_CHINCHIPE', 'Zamora Chinchipe'), ('SUCUMBIOS', 'Sucumbíos'), ('ORELLANA', 'Orellana'), ('SANTO_DOMINGO', 'Santo Domingo de los Tsáchilas'), ('GALAPAGOS', 'Galápagos')], max_length=50, verbose_name='Provincia')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
