# Generated by Django 5.2.5 on 2025-10-03 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(max_length=13, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_movil',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Número de teléfono inválido. Puede incluir código de país (+593).', regex='^\\+?\\d{7,15}$')], verbose_name='Teléfono Móvil'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('tipo_documento', 'numero_documento'), name='unique_tipo_numero'),
        ),
    ]
