# Generated by Django 5.2.5 on 2025-10-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_activo_alter_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='aplica_descuento',
            field=models.BooleanField(default=False, verbose_name='Aplica Descuento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='requiere_envio',
            field=models.BooleanField(default=False, verbose_name='Requiere Envío'),
        ),
    ]
