# Generated by Django 5.2.5 on 2025-08-27 04:13

import django.core.validators
import proveedores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_proveedor', models.CharField(choices=[('LOCAL', 'Local (Ecuador)'), ('EXTERIOR', 'Exterior')], max_length=10, verbose_name='Tipo de Proveedor')),
                ('tipo_identificacion', models.CharField(max_length=20, verbose_name='Tipo de Identificación')),
                ('numero_identificacion', models.CharField(max_length=20, unique=True, verbose_name='Número de Identificación')),
                ('razon_social', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Razón Social / Nombre')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('tipo_productos', models.CharField(choices=[('BIENES', 'Bienes'), ('SERVICIOS', 'Servicios'), ('AMBOS', 'Ambos')], max_length=10, verbose_name='Tipo de Proveedor (Bienes/Servicios/Ambos)')),
                ('moneda_pago', models.CharField(choices=[('USD', 'Dólar estadounidense'), ('EUR', 'Euro'), ('OTRA', 'Otra')], max_length=10, verbose_name='Moneda de Pago')),
                ('cuenta_bancaria', models.CharField(max_length=34, validators=[proveedores.models.validar_cuenta_bancaria], verbose_name='Cuenta Bancaria')),
                ('plazo_entrega', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Plazo de Entrega (días hábiles)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['razon_social'],
            },
        ),
    ]
