# Generated by Django 5.2.5 on 2025-08-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(editable=False, max_length=100, verbose_name='Ciudad (capital)'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='pais',
            field=models.CharField(choices=[('Ecuador', 'Ecuador'), ('Colombia', 'Colombia'), ('Perú', 'Perú'), ('Chile', 'Chile'), ('Argentina', 'Argentina'), ('España', 'España'), ('México', 'México'), ('Estados Unidos', 'Estados Unidos'), ('Alemania', 'Alemania'), ('Francia', 'Francia')], max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_identificacion',
            field=models.CharField(choices=[('CEDULA', 'Cédula'), ('RUC', 'RUC'), ('PASAPORTE', 'Pasaporte'), ('ID_TRIBUTARIO', 'ID Tributario Extranjero')], max_length=20, verbose_name='Tipo de Identificación'),
        ),
    ]
