# Generated by Django 5.2.5 on 2025-09-03 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_proveedor_ciudad_alter_proveedor_pais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.IntegerField(max_length=10, verbose_name='Teléfono'),
        ),
    ]
