# Generated by Django 5.2.5 on 2025-08-27 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('proveedores', '0002_alter_proveedor_ciudad_alter_proveedor_pais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adquisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha_arribo', models.DateField()),
                ('tipo_carga', models.CharField(choices=[('SUELTA', 'Suelta'), ('EMBALADO', 'Embalado'), ('PALLETS', 'Pallets')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='AdquisicionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(blank=True, max_length=100, null=True)),
                ('vigencia_lote', models.DateField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('adquisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='adquisiciones.adquisicion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
