# Generated by Django 5.2.5 on 2025-10-03 16:11

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adquisiciones', '0001_initial'),
        ('productos', '0004_remove_producto_cantidad_inventario_and_more'),
        ('proveedores', '0004_alter_proveedor_direccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAdquisicion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_orden', models.CharField(db_index=True, editable=False, max_length=20)),
                ('fecha_arribo', models.DateField()),
                ('tipo_carga', models.CharField(choices=[('SUELTA', 'Suelta'), ('EMBALADO', 'Embalado'), ('PALLETS', 'Pallets'), ('CONTENEDOR', 'Contenedor'), ('GRANEL', 'Granel')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_PROCESO', 'En Proceso'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical adquisicion',
                'verbose_name_plural': 'historical adquisicions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAdquisicionDetalle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('lote', models.CharField(blank=True, max_length=100, null=True)),
                ('vigencia_lote', models.DateField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('peso_unitario_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volumen_unitario_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Detalle de Adquisición',
                'verbose_name_plural': 'historical Detalles de Adquisiciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterModelOptions(
            name='adquisiciondetalle',
            options={'verbose_name': 'Detalle de Adquisición', 'verbose_name_plural': 'Detalles de Adquisiciones'},
        ),
        migrations.RemoveField(
            model_name='adquisicion',
            name='confirmado',
        ),
        migrations.AddField(
            model_name='adquisicion',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_PROCESO', 'En Proceso'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20),
        ),
        migrations.AddField(
            model_name='adquisiciondetalle',
            name='peso_unitario_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='adquisiciondetalle',
            name='volumen_unitario_m3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='adquisicion',
            name='tipo_carga',
            field=models.CharField(choices=[('SUELTA', 'Suelta'), ('EMBALADO', 'Embalado'), ('PALLETS', 'Pallets'), ('CONTENEDOR', 'Contenedor'), ('GRANEL', 'Granel')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='adquisicion',
            constraint=models.UniqueConstraint(fields=('proveedor', 'fecha_arribo'), name='unique_proveedor_fecha'),
        ),
        migrations.AddField(
            model_name='historicaladquisicion',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaladquisicion',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='historicaladquisiciondetalle',
            name='adquisicion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='adquisiciones.adquisicion'),
        ),
        migrations.AddField(
            model_name='historicaladquisiciondetalle',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaladquisiciondetalle',
            name='producto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='productos.producto'),
        ),
    ]
