# Generated by Django 5.2.5 on 2025-10-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adquisiciones', '0002_historicaladquisicion_historicaladquisiciondetalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adquisiciondetalle',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='historicaladquisiciondetalle',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
