# Generated by Django 5.2.5 on 2025-10-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adquisiciones', '0003_alter_adquisiciondetalle_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adquisicion',
            name='inventario_procesado',
            field=models.BooleanField(default=False, verbose_name='Inventario Procesado'),
        ),
        migrations.AddField(
            model_name='historicaladquisicion',
            name='inventario_procesado',
            field=models.BooleanField(default=False, verbose_name='Inventario Procesado'),
        ),
    ]
